version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes
file_exists_behavior: OVERWRITE
hooks:
  # BeforeInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root
  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: scripts/removefile.sh
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: scripts/removefile.sh
  #     timeout: 300
  #     runas: root
