version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum install https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm -y
      - sudo amazon-linux-extras install epel -y
      - sudo yum -y install mysql-community-server

      # SQLite 빌드를 최적화하기 위한 작업 추가
      - sudo yum install gcc -y
      - sudo yum install sqlite-devel -y
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - echo "pre_build complete"

  build:
    commands:
      - python manage.py test
      - echo "Build complete"

  post_build:
    commands:
      - echo "post_Build start"
      # 불필요한 파일 제거를 최적화
      - rm -rf static/ venv/
      - tar -czvf django-ecommerce.tar.gz src/
      - echo "post_build complete"

artifacts:
  files:
    - django-ecommerce.tar.gz
  discard-paths: yes
